config/routes.rb
Rails.application.routes.draw do
  root 'velos#index'
  
  
  resources :pannes do
    resources :reparations
  end
  resources :velos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/panne.rb
class Panne < ApplicationRecord
    belongs_to :velo

    has_many :reparations, dependent: :destroy

    validates :explication_de_la_panne, :presence => true
end

app/models/reparation.rb
class Reparation < ApplicationRecord
    belongs_to :panne

    validates :reparation_faite, :maniere_de_reparer ,:materiel_utiliser, :presence => true
end

app/models/velo.rb
class Velo < ApplicationRecord
    #Lorsqu'un vélo est supprimé, la panne sur le vélo l'est aussi
    has_many :pannes, dependent: :destroy

    validates :nom_de_velo, :presence => true, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pannes_controller.rb
class PannesController < ApplicationController
  def index
    @pannes = Panne.all
  end

  def show
    @panne = Panne.find(params[:id])
    @reparation = Reparation.new
    @reparations = @panne.reparations
  end

  def new
    @panne = Panne.new
  end

  def edit
    @panne = Panne.find(params[:id])
  end

  def update
    @panne = Panne.find(params[:id])

    respond_to do |format|
      if @panne.update(panne_params)
        format.html { redirect_to panne_url(@panne), notice: "La panne a bien été modifiée" }
      else
        render :edit
      end
    end
  end

  def create
    @panne = Panne.new(panne_params)

    if @panne.save
      respond_to do |format|
        format.html { redirect_to panne_url(@panne), notice: "La panne a bien été créée" }
      end
    else
      render :new
    end
  end

  def destroy
    @panne = Panne.find(params[:id])
    @panne.destroy
    redirect_to pannes_path, status: :see_other, notice: "La panne a bien été supprimée"
  end

  private

  def panne_params
    params.require(:panne).permit(:categorie_de_panne, :explication_de_la_panne, :velo_id)
  end
end

app/controllers/reparations_controller.rb
class ReparationsController < ApplicationController
  def create
    @panne = Panne.find(params[:panne_id])
    @reparation = @panne.reparations.create(reparation_params)

    if @reparation.save
      respond_to do |format|
        format.html { redirect_to panne_url(@panne), notice: "La reparation a bien été créée" }
      end
    end
  end

  def destroy
    @panne = Panne.find(params[:panne_id])
    @reparation = Reparation.find(params[:id])
    @reparation.destroy
    redirect_to @panne, status: :see_other, notice: "La reparation a bien été supprimée"
  end

  private

  def reparation_params
    params.require(:reparation).permit(:reparation_faite, :maniere_de_reparer, :materiel_utiliser)
  end
end

app/controllers/velos_controller.rb
class VelosController < ApplicationController
  def index
    @velos = Velo.includes(:pannes).all
  end

  def show
    @velo = Velo.find(params[:id])
  end

  def new
    @velo = Velo.new
  end

  def edit
    @velo = Velo.find(params[:id])
  end

  def update
    @velo = Velo.find(params[:id])

    respond_to do |format|
      if @velo.update(velo_params)
        format.html { redirect_to velo_url(@velo), notice: "Le vélo a bien été modifier" }
      else
        render :edit
      end
    end
  end

  def create
    @velo = Velo.new(velo_params)

    if @velo.save
      respond_to do |format|
        format.html { redirect_to velo_url(@velo), notice: "Le vélo a bien été crée" }
      end
    else
      render :new
    end
  end

  def destroy
    @velo = Velo.find(params[:id])
    @velo.destroy
    redirect_to velos_path, status: :see_other, notice: "Le vélo a bien été supprimé"
  end

  private

  def velo_params
    params.require(:velo).permit(:nom_de_velo, :type_de_velo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pannes_helper.rb
module PannesHelper
end

app/helpers/reparations_helper.rb
module ReparationsHelper
end

app/helpers/velos_helper.rb
module VelosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bikes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pannes/_form.html.erb
<%= form_for @panne do |form| %>

    <%= form.label :categorie_de_panne %>
    <%= form.select :categorie_de_panne, 
        ["probleme de roue","probleme de moteur", "cassette usée", "chaîne usée"] %>

    <%= form.label :explication_de_la_panne %>
    <%= form.text_area :explication_de_la_panne %>

    <%= form.label :velo_id %>
    <%= form.select :velo_id, Velo.all.map {|contenu| [contenu.nom_de_velo, contenu.id]} %>

    <%= form.submit %>

<% end %>

app/views/pannes/edit.html.erb
<h1>Pannes</h1>

<%= render 'form' %>

<%= link_to "Retour", panne_path(@panne), 
    {:style=>'color:#FFFFFF;', :class => "boutton_retour margin"} %>

app/views/pannes/index.html.erb
<div class="header">
    <h1>Pannes</h1>
    <%= link_to "Voir les vélos", velos_path %>
</div>

<p style="color: green"><%= notice %></p>

<% @pannes.each do |panne| %>
    <div class="cartes_de_presentation">
        <p>
            Catégorie de la panne : <%= panne.categorie_de_panne %>
        </p>
        
        <p>
            Explication de la panne :
        </p>
        
        <%= content_tag :p, class: "text_explications_index" do -%>
            <%= panne.explication_de_la_panne %>
        <% end -%>

        <br>
        
        <% if panne.reparations %>
            <% panne.reparations.each do |reparation| %>
                <p>
                    La réparation faite sur cette panne : 
                <p>
                <%= reparation.reparation_faite %>
            <% end %>
        <% end %>
        
        <br>

        <%= link_to "Details", panne_path(panne.id), 
            {:style=>'color:#FFFFFF;', :class => "boutton_details margin"} %>
    </div>
<% end %>

<br>

<%= link_to "Nouvelle panne", new_panne_path, 
    {:style=>'color:#FFFFFF;', :class => "boutton_nouveau margin" } %>

app/views/pannes/new.html.erb
<h1>Pannes</h1>

<%= render 'form' %>

<br>

<%= link_to "Retour", pannes_path, {:style=>'color:#FFFFFF;', :class => "boutton_retour"} %>

app/views/pannes/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="cartes_de_presentation">
    <% if @panne.velo %>
        <h1>Nom du vélo : <%= @panne.velo.nom_de_velo %></h1>
    <%end%>

    <h2>Catégorie de probleme : <%= @panne.categorie_de_panne %></h2>

    <strong>Explications :</strong>
    <%= content_tag :p, class: "text_explications_show" do -%>
        <%= @panne.explication_de_la_panne %>
    <% end -%>

    <%= render 'reparations/reparations' %>
</div>

<%= render 'reparations/form' %>

<br>

<%= link_to "Modifier la panne", edit_panne_path, 
    {:style=>'color:#FFFFFF;', :class => "boutton_details"} %>

<br>

<%= link_to "Supprimer la fiche de cette panne", @panne,
    data: { turbo_method: :delete, 'turbo-confirm': 'Etes-vous sure ?' } %>

<br>

<%= link_to "Retour", pannes_path, 
    {:style=>'color:#FFFFFF;', :class => "boutton_retour"} %>

app/views/reparations/_form.html.erb
<%= form_for ([@panne, @reparation]) do |form| %>

    <%= form.label "Réparation faite le :" %>
    <%= form.text_field :reparation_faite %>

    <%= form.label :maniere_de_reparer %>
    <%= form.text_area :maniere_de_reparer %>
    
    <%= form.label :materiel_utiliser %>
    <%= form.text_area :materiel_utiliser %>

    <%= form.submit %>

<% end %>

app/views/reparations/_reparations.html.erb
<% @reparations.each do |reparation| %>
    <ul>
        <li>
            <p>Date de la réparations : <%= reparation.reparation_faite %></p>
            
            <p>La date de la réparations : <%= reparation.maniere_de_reparer %></p>
            
            <p>materiel utiliser pour la panne : <%= reparation.materiel_utiliser %></p>

            <%= link_to "Supprimé", panne_reparation_path(reparation.panne_id, reparation.id), 
                data: { turbo_method: :delete }  %>
        </li>
    </ul>
<% end %>

app/views/velos/_form.html.erb
<%= notice %>
<%= form_for @velo do |form| %>

    <%= form.label :nom_de_velo %>
    <%= form.text_field :nom_de_velo %>

    <%= form.label :type_de_velo %>
    <%= form.select :type_de_velo, ["mécanique","éléctrique"] %>

    <%= form.submit %>

<% end %>

app/views/velos/edit.html.erb
<h1>Vélos</h1>

<%= render 'form' %>

<%= link_to "Retour", velo_path(@velo), 
    {:style=>'color:#FFFFFF;', :class => "boutton_retour margin"} %>

app/views/velos/index.html.erb
<div class="header">
    <h1>Vélos</h1>
    <%= link_to "Voir les pannes", pannes_path %>
</div>

<p style="color: green"><%= notice %></p>

<% @velos.each do |velo| %>
    <div class="cartes_de_presentation">
        <p>Nom du velo : <%= velo.nom_de_velo %></p>

        <p>Type de velo : <%= velo.type_de_velo %></p>

        <% if velo.pannes %>
            <% velo.pannes.each do |panne| %>
                <p>La panne : <p>
                <%= content_tag :p, class: "text_explications_index" do -%>
                    <%= panne.explication_de_la_panne %>
                <% end -%>
                <p>La réparation faite sur cette panne : <%= panne.reparations.ids %><br>
            <% end %>
        <% end %>
        
        <br>
        
        <%= link_to "Details", velo_path(velo.id), 
            {:style=>'color:#FFFFFF;', :class => "boutton_details margin"} %>
    </div>
<% end %>

<br>

<%= link_to "Nouveau vélo", new_velo_path, 
    {:style=>'color:#FFFFFF;', :class => "boutton_nouveau margin"} %>

app/views/velos/new.html.erb
<h1>Vélos</h1>

<%= render 'form' %>

<br>

<%= link_to "Retour", velos_path, 
    {:style=>'color:#FFFFFF;', :class => "boutton_retour margin"} %>

app/views/velos/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="cartes_de_presentation">
    <h1>
        Le numéro du vélo : <%= @velo.nom_de_velo %>
    </h1>

    <p>
        Le type de vélo : <%= @velo.type_de_velo %>
    </p>

    <% @velo.pannes.each do |panne| %>
        <strong>La panne :</strong>
        
        <%= content_tag :p, class: "text_explications_show" do -%>
            <%= panne.explication_de_la_panne %>
        <% end -%>

        <p>
            <%= link_to "Voir la panne", panne, 
                {:style=>'color:#FFFFFF;', :class => "boutton_details margin"} %>
        </p>
    <% end %>

    <br>

    <%= link_to "Ajouter une panne a ce vélo", new_panne_path, 
        {:style=>'color:#FFFFFF;', :class => "boutton_ajouter_une_panne margin"} %>

    <br>

    <%= link_to "Modifier la fiche du vélo", edit_velo_path, 
        {:style=>'color:#FFFFFF;', :class => "boutton_modifier margin"} %>

    <br>

    <%= link_to "Supprimer la fiche de ce vélo et la panne", @velo, 
        data: { turbo_method: :delete } %> <br>
</div>

<br>

<%= link_to "Retour", velos_path, 
    {:style=>'color:#FFFFFF;', :class => "boutton_retour margin"} %>